- README.md
- front-end/bite-buddy/src/App.jsx
- front-end/bite-buddy/src/index.css
- front-end/bite-buddy/src/pages/Login.jsx
- front-end/bite-buddy/src/pages/Signup.jsx
Tasks #47 #49 simple Login and Signup pages linked.
> Create Login and Signup Pages

- front-end/bite-buddy/src/App.jsx
- front-end/bite-buddy/src/components/Hamburger.jsx
- front-end/bite-buddy/src/components/HamburgerDropdown.css
> Added hamburger component

- front-end/bite-buddy/src/pages/Challenges.css
- front-end/bite-buddy/src/pages/Challenges.jsx
Implemented challenge page and challenge css
> Implemented challenge page and challenge css

- front-end/bite-buddy/src/App.jsx
- front-end/bite-buddy/src/components/Footer.jsx
- front-end/bite-buddy/src/index.css
- front-end/bite-buddy/src/pages/Login.jsx
- front-end/bite-buddy/src/pages/Signup.jsx
> Add mobile-responsiveness styling to navbar/login/signup

- front-end/bite-buddy/src/App.jsx
- front-end/bite-buddy/src/components/Footer.jsx
- front-end/bite-buddy/src/index.css
- front-end/bite-buddy/src/pages/Login.jsx
- front-end/bite-buddy/src/pages/Signup.jsx
- front-end/bite-buddy/src/pages/Signup_profile.jsx
> Combine hamburger menu and navbar to highlight active tab

- front-end/bite-buddy/src/App.jsx
- front-end/bite-buddy/src/index.css
- front-end/bite-buddy/src/pages/Activity_Tracker.jsx
- front-end/bite-buddy/src/pages/Home.jsx
> Add link to activity tracker and implement activity history

- front-end/bite-buddy/src/App.jsx
- front-end/bite-buddy/src/components/Footer.jsx
- front-end/bite-buddy/src/index.css
- front-end/bite-buddy/src/pages/Activity_Tracker.jsx
- front-end/bite-buddy/src/pages/Home.jsx
- front-end/bite-buddy/src/pages/Login.jsx
- front-end/bite-buddy/src/pages/Profile.jsx
- front-end/bite-buddy/src/pages/Signup.jsx
- front-end/bite-buddy/src/pages/Signup_profile.jsx
Made changes to Profile.jsx and index.css
> Added Profile Page

- front-end/bite-buddy/package.json
- front-end/bite-buddy/src/components/Footer.jsx
- front-end/bite-buddy/src/index.css
- front-end/bite-buddy/src/pages/Activity_Tracker.jsx
> Add icons to navbar

- front-end/bite-buddy/package.json
- front-end/bite-buddy/src/components/Footer.jsx
- front-end/bite-buddy/src/components/Hamburger.jsx
- front-end/bite-buddy/src/components/HamburgerDropdown.css
- front-end/bite-buddy/src/pages/Challenges.css
- front-end/bite-buddy/src/pages/Challenges.jsx
added axios, fixed hamburger and challenges css, added mockaroo to challenges
> added axios, fixed hamburger and challenges css, added mockaroo to challenges

- front-end/bite-buddy/src/pages/Challenges.css
- front-end/bite-buddy/src/pages/Challenges.jsx
react-router-dom Link to navigate challenges page
debugging reload
> react-router-dom Link to navigate challenges page

- front-end/bite-buddy/src/components/Footer.jsx
- front-end/bite-buddy/src/index.css
- front-end/bite-buddy/src/pages/Challenges.jsx
- front-end/bite-buddy/src/pages/Record.jsx
> create rough draft of record activity

- front-end/bite-buddy/src/Profile.css
- front-end/bite-buddy/src/pages/Profile.jsx
> Create Working Profile Page

- front-end/bite-buddy/src/pages/Recipes.jsx
- front-end/bite-buddy/src/recipes.css
> Recipe Page!

- front-end/bite-buddy/README.md
- front-end/bite-buddy/index.html
- front-end/bite-buddy/package.json
- front-end/bite-buddy/src/pages/Recipes.jsx
> Mockeroo Setup

- front-end/bite-buddy/src/pages/Challenges.css
made into square top left corner
> fixed close button css

- front-end/bite-buddy/src/Home.css
- front-end/bite-buddy/src/pages/Home.jsx
> Add Home Page

- back-end/src/app.mjs
- front-end/src/axiosConfig.js
- front-end/src/pages/Challenges.jsx
> mockaroo for challenges and cors configs

- back-end/package.json
- back-end/src/app.mjs
- back-end/src/auth.mjs
- back-end/src/server.mjs
- front-end/package.json
- front-end/src/Home.css
- front-end/src/axiosConfig.js
- front-end/src/pages/Activity_Tracker.jsx
- front-end/src/pages/Challenges.css
- front-end/src/pages/Challenges.jsx
- front-end/src/pages/Home.jsx
- front-end/src/pages/Login.jsx
- front-end/src/pages/Signup.jsx
> login signup routs and suggest recipie page and route

- front-end/src/Home.css
- front-end/src/pages/Home.jsx
> share recipe text area css change

- back-end/src/app.mjs
- front-end/src/components/CompletionModal.jsx
- front-end/src/components/IngredientsList.jsx
- front-end/src/components/NoRecipes.jsx
- front-end/src/components/RecipeSteps.jsx
- front-end/src/pages/Record.jsx
> changed closing modal logic

- back-end/src/app.mjs
- front-end/src/pages/Profile.jsx
> migrate profile mockaroo

- front-end/src/index.css
- front-end/src/pages/Progress_Tracker.jsx
> progress tracker with percent completion

- back-end/models/activity.mjs
- back-end/models/recipe.mjs
- back-end/package.json
- front-end/src/pages/Profile.jsx
> Fix schemas and add signout

- back-end/models/activity.mjs
- back-end/models/recipe.mjs
- back-end/src/app.mjs
- front-end/src/components/IngredientsList.jsx
- front-end/src/components/RecipeSteps.jsx
- front-end/src/components/Timer.css
- front-end/src/components/Timer.jsx
- front-end/src/pages/Recipes.jsx
- front-end/src/pages/Record.jsx
> refactor recipes and record activity

- back-end/models/recipe.mjs
- back-end/src/app.mjs
- front-end/src/components/Footer.jsx
- front-end/src/pages/Challenges.jsx
- front-end/src/pages/Recipes.jsx
- front-end/src/pages/Record.jsx
> remove hamburger, and reroute challenges to use recipes mongo schema

- back-end/src/app.mjs
- front-end/src/Home.css
- front-end/src/components/ShareRecipe.jsx
- front-end/src/index.css
- front-end/src/pages/Home.jsx
- front-end/src/pages/Recipes.jsx
> Implement share recipe mongo routing and new ui

- front-end/src/Profile.css
- front-end/src/pages/Profile.jsx
> added back progress link in profile

- back-end/middleware/validators.mjs
- back-end/package.json
- back-end/src/app.mjs
- package.json
Data validation failures not visible in UI
> Data validation for update user profile

- back-end/src/app.mjs
- front-end/src/pages/Signup_profile.jsx
> Edit profile bugs
